version: 2.1

orbs:
  win: circleci/windows@2.2.0

references:
  paths:
    test-results: &TEST_RESULTS /tmp/test-results
    win-test-results: &WIN_TEST_RESULTS c:\Users\circleci\AppData\Local\Temp\test-results
    win-go-dir: &WIN_WORKING_DIR c:\gopath\src\github.com\hashicorp\hcl
    win-gomod-dir: &WIN_GOMOD_DIR c:\Windows\system32\config\systemprofile\go\pkg\mod
  environment: &ENVIRONMENT
    GOMAXPROCS: 4
    GO111MODULE: "on"
    GOPROXY: https://proxy.golang.org/
    TEST_RESULTS_DIR: &TEST_RESULTS_DIR /tmp/test-results/hcl
    WIN_TEST_RESULTS: *WIN_TEST_RESULTS
    WIN_WORKING_DIR: *WIN_WORKING_DIR
    WIN_GOMOD_DIR: *WIN_GOMOD_DIR

commands:
  git-verify:
    steps:
      - run: 
          name: "Verify no code was generated"
          command: |
            if [[ -z $(git status --porcelain) ]]; then
              echo "Git directory is clean."
            else
              echo "Git is dirty. Run `make fmt` and `make generate` locally and commit any formatting fixes or generated code."
              git status --porcelain
              exit 1
            fi

  run-gotests:
    parameters:
      cmd:
        type: string
      prefix:
        type: string
    steps:
      - run:
          name: "Run go tests"
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            echo "Running $(echo $PACKAGE_NAMES | wc -w) packages"
            echo $PACKAGE_NAMES
            << parameters.cmd >> --format=short-verbose --junitfile $TEST_RESULTS_DIR/gotestsum-report.xml -- -p 2 -cover -coverprofile=<< parameters.prefix >>_cov_$CIRCLE_NODE_INDEX.part $PACKAGE_NAMES
        
jobs:
  go-checks:
    docker:
      - image: circleci/golang:<< parameters.go-version >>
    environment: 
      <<: *ENVIRONMENT
    parameters:
      go-version:
        type: string
    steps:
      - checkout
      - run: go mod verify
      - run: make fmt
      - git-verify

  linux-tests:
    docker:
      - image: circleci/golang:<< parameters.go-version >>
    environment: 
      <<: *ENVIRONMENT
    parameters:
      go-version:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: mkdir -p $TEST_RESULTS_DIR
      - run-gotests:
          cmd: "gotestsum"
          prefix: "linux"

      # save coverage report parts
      - persist_to_workspace:
          root: .
          paths:
            - linux_cov_*.part

      - store_test_results:
          path: *TEST_RESULTS_DIR
      - store_artifacts:
          path: *TEST_RESULTS_DIR

  win-tests:
    executor: 
      name: win/default
      shell: bash --login -eo pipefail
    environment:
      <<: *ENVIRONMENT
    working_directory: *WIN_WORKING_DIR
    parameters:
      go-version:
        type: string
      gotestsum-version:
        type: string
    steps: 
      - run: git config --global core.autocrlf false
      - checkout
      - attach_workspace:
          at: .
      - git-verify
      - run: 
          name: Setup (remove pre-installed go v1.12)
          command: |
            rm -rf "c:\Go"
            mkdir -p $TEST_RESULTS_DIR

      - restore_cache:
          keys:
            - windows-golang-<< parameters.go-version >>-cache
            - windows-gomod-cache-{{ checksum "go.mod" }}

      - run: 
          name: Install go version << parameters.go-version >>
          command: | 
            if [ ! -d "c:\go" ]; then
              echo "Cache not found, installing new version of go"
              curl --fail --location https://dl.google.com/go/go<< parameters.go-version >>.windows-amd64.zip --output go.zip
              unzip go.zip -d "/c"
            fi

      - run: 
          name: Go mod download
          command: |
            go mod verify
            go mod download
  
      - save_cache:
          key: windows-golang-<< parameters.go-version >>-cache
          paths:
            - /go

      - save_cache:
          key: windows-gomod-cache-{{ checksum "go.mod" }}
          paths:
            - *WIN_GOMOD_DIR

      - run:
          name: Install gotestsum
          command: |
            curl --fail --location https://github.com/gotestyourself/gotestsum/releases/download/v<< parameters.gotestsum-version >>/gotestsum_<< parameters.gotestsum-version >>_windows_amd64.tar.gz --output gotestsum.tar.gz
            tar -xvzf gotestsum.tar.gz

      - run-gotests:
          cmd: "./gotestsum.exe"
          prefix: "win"

      # save coverage report parts
      - persist_to_workspace:
          root: .
          paths:
            - win_cov_*.part

      - store_test_results:
          path: *WIN_TEST_RESULTS
      - store_artifacts:
          path: *WIN_TEST_RESULTS
          
workflows:
  hcl:
    jobs:
      - linux-tests:
          matrix:
            parameters:
              go-version: ["1.14"]
          name: linux-test-go-<< matrix.go-version >>
      - win-tests:
          matrix:
            parameters:
              go-version: ["1.14"]
              gotestsum-version: ["0.4.1"]
          name: win-test-go-<< matrix.go-version >>
